<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.3" />
    <PackageReference Include="Grpc.Tools" Version="2.65.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="APP\**\*.proto" GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libs\bili-kernel\src\Authorizers\Authorizers.Tv\Authorizers.Tv.csproj" />
    <ProjectReference Include="..\Libs\bili-kernel\src\BiliKernel.Abstractions\BiliKernel.Abstractions.csproj" />
    <ProjectReference Include="..\Libs\bili-kernel\src\BiliKernel.Core\BiliKernel.Core.csproj" />
    <ProjectReference Include="..\Libs\bili-kernel\src\Services\Services.Media\Services.Media.csproj" />
  </ItemGroup>

</Project>
